[package]
name = "sowm-common"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcode = { version = "0.6.3", features = ["serde"] }
directories = "6.0.0"
homedir = "0.3.4"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
toml = "0.8.19"
users = "0.11.0"
