[package]
name = "sowmd"
version = "0.1.0"
edition = "2021"
default-run = "sowmd"

[dependencies]
ctrlc = "3.4.5"
interprocess = "2.2.2"
libc = "0.2.169"
user = "0.1.1"
users = "0.11.0"

sowm-common = { path = "../sowm-common/" }
